---
title: "data scraper"
output: html_document
date: '2022-11-01'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(rvest)
library(dplyr)
library(magrittr)
library(XML)
library(RCurl)
library(RTidyHTML)
library(httr)
```



```{r}
clean_df = function(df, week) {
  
  # select the rows we need
  df = df %>%
    select(id, start_time, away_team_id, home_team_id, winning_team_id, league_name, season, teams, boxscore, odds, teams)
  
  # add final scores
  df$home_points = df$boxscore$total_home_points
  df$away_points = df$boxscore$total_away_points
  
  # remove unnecessary rows
  df = df %>%
    select(-c(boxscore))
  
  # unnest the odds dataframe
  
  for (i in 1:length(df$odds)) {
    odds = df$odds[[i]]
    if ("meta" %in% colnames(odds)) {
      df$odds[[i]] = odds %>%
        select(-c(meta))
    }
  }
  
  df = df %>% unnest(c(odds))
  
  # remove unnecessary variables in the odds
  df = df %>%
    select(-c(ml_home_public, ml_away_public, spread_home_public, spread_away_public, total_under_public, total_over_public, ml_home_money, ml_away_money, 
              spread_home_money, total_over_money, total_under_money, num_bets, type, inserted, line_status))
  
  # add the week
  df = df %>%
    mutate(week = week)
  
  return(df)
}
```

# NFL data

```{r}
url = "https://api.actionnetwork.com/web/v1/scoreboard/nfl?period=game&bookIds=15,30,76,75,123,69,68,972,71,247,79&seasonType=reg"
nfl_2022_df = NULL
for (i in 1:7) {
  temp_url = param_set(url, "week", i)
  resp = GET(temp_url, user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"))
  resp_df = jsonlite::fromJSON(content(resp, "text"))$games
  nfl_2022_df = rbind(nfl_2022_df, clean_df(resp_df, i))
  Sys.sleep(1)
  print(paste("finished week",i))
}
```

```{r}
save(nfl_2022_df, file = "nfl_2022_df.rdata")
```

# NCAA Football data

```{r}
url = "https://api.actionnetwork.com/web/v1/scoreboard/ncaaf?period=game&bookIds=15,30,76,75,123,69,68,972,71,247,79&seasonType=reg"
ncaaf_2022_df = NULL
for (i in 1:9) {
  temp_url = param_set(url, "week", i)
  resp = GET(temp_url, user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"))
  resp_df = jsonlite::fromJSON(content(resp, "text"))$games
  ncaaf_2022_df = rbind(ncaaf_2022_df, clean_df(resp_df, i))
  Sys.sleep(1)
  print(paste("finished week",i))
}
```

```{r}
save(ncaaf_2022_df, file = "ncaaf_2022_df.rdata")
```


# NBA Data

```{r}
url = "https://api.actionnetwork.com/web/v1/scoreboard/nba?period=game&bookIds=15,30,76,75,123,69,68,972,71,247,79"
nba_2022_df = NULL
for (i in 18:30) {
  temp_url = param_set(url, "date", paste(202210, i, sep = ""))
  resp = GET(temp_url, user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"))
  resp_df = jsonlite::fromJSON(content(resp, "text"))$games
  nba_2022_df = rbind(nba_2022_df, clean_df(resp_df, i))
  Sys.sleep(1)
  print(paste("finished", i))
}

seq(as.Date("2021-10-10"), as.Date("2022-04-10"), by="days")

as.Date("2021-10-10", format=c('%m %d %y'))
```

