---
title: "Line Movement Scraper"
output: html_document
date: '2022-11-02'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
library(rvest)
library(dplyr)
library(magrittr)
library(XML)
library(RCurl)
library(httr)
```



```{r}
load("betting_data.rdata")
```

```{r}
load("nfl_movement_2018_new.rdata")
load("nfl_movement_2020_new.rdata")

load("nfl_df_early.rdata")
```


```{r}
NFL2016 <- nfl_df_early %>%
  filter(league_name == "nfl") %>%
  filter(season== 2016) %>%
  group_by(id) %>%
  summarise(t = n())
  
NFL2015 <- nfl_df_early %>%
  filter(league_name == "nfl") %>%
  filter(season== 2015) %>%
  group_by(id) %>%
  summarise(t = n())
  
NFL2014 <- nfl_df_early %>%
  filter(league_name == "nfl") %>%
  filter(season== 2014) %>%
  group_by(id) %>%
  summarise(t = n())
  
NFL2013 <- nfl_df_early %>%
  filter(league_name == "nfl") %>%
  filter(season== 2013) %>%
  group_by(id) %>%
  summarise(t = n())
  
NFL2012 <- nfl_df_early %>%
  filter(league_name == "nfl") %>%
  filter(season== 2012) %>%
  group_by(id) %>%
  summarise(t = n())
```


```{r}
betting_data <- betting_data %>%
  mutate(GB_Index = row_number()) %>%
  mutate(GB_Index = as.numeric(GB_Index))

NFL <- betting_data %>%
  filter(league_name == "nfl") %>%
  filter(season == 2022 | season == 2021 | season == 2019 | season == 2017) %>%
  group_by(id) %>%
  summarise(t = n())

NFL2018 <- nfl_movement_2018 %>%
  filter(league_name == "nfl") %>%
  group_by(id) %>%
  summarise(t = n())

NFL2020 <- nfl_movement_2020 %>%
  filter(league_name == "nfl") %>%
  group_by(id) %>%
  summarise(t = n())

NFLEarly <- nfl_df_early %>%
  filter(league_name == "nfl") %>%
  group_by(id) %>%
  summarise(t = n())

NCAAF <- betting_data %>%
  filter(league_name == "ncaaf") %>%
  filter(season == 2022 | season == 2021) %>%
  group_by(id) %>%
  summarise(t = n())

MLB <- betting_data %>%
  filter(league_name == "mlb") %>%
  filter(season == 2022 | season == 2021) %>%
  group_by(id) %>%
  summarise(t = n())

NHL <- betting_data %>%
  filter(league_name == "nhl") %>%
  filter(season == 2022 | season == 2021) %>%
  group_by(id) %>%
  summarise(t = n())

NBA <- betting_data %>%
  filter(league_name == "nba") %>%
  filter(season == 2022 | season == 2021) %>%
  group_by(id) %>%
  summarise(t = n())
```


game_id = 132525
url = "https://api.actionnetwork.com/web/v1/games/"
url = paste(url, game_id, "/oddshistory")
resp = GET(url, user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"))
resp_df = jsonlite::fromJSON(content(resp, "text"))$odds

resp_df <- resp_df %>%
  mutate(id = 132525)



```{r}
clean_df = function(df, id) {
  
  # select the rows we need
  df = df %>%
    select(id, start_time, away_team_id, home_team_id, ml_away, ml_home, spread_away, spread_home, total,away_total, home_total, league_name )
  
  # remove unnecessary variables in the odds
  df = df %>%
    select(-c(ml_home_public, ml_away_public, spread_home_public, spread_away_public, total_under_public, total_over_public, ml_home_money, ml_away_money, 
              spread_home_money, total_over_money, total_under_money, num_bets, type, inserted, line_status, spread_away_line, spread_home_line))
  
  return(df)
}
```


```{r}
NFL_movement_df = NULL

for (id in NFL$id) {
  
  game_id = id
  url = "https://api.actionnetwork.com/web/v1/games/"
  url = paste(url, game_id, "/oddshistory")
  resp = GET(url, user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko)    Chrome/106.0.0.0 Safari/537.36"))
  resp_df = jsonlite::fromJSON(content(resp, "text"))$odds
  resp_df <- resp_df %>%
    mutate(id = game_id) %>%
    mutate(league = "nfl")
    NFL_movement_df = rbind(NFL_movement_df, resp_df)

  print(paste("finished game",id))
  }

```

```{r}
NFL_movement_2018_df = NULL

for (id in NFL2018$id) {
  
  game_id = id
  url = "https://api.actionnetwork.com/web/v1/games/"
  url = paste(url, game_id, "/oddshistory")
  resp = GET(url, user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko)    Chrome/106.0.0.0 Safari/537.36"))
  resp_df = jsonlite::fromJSON(content(resp, "text"))$odds
  resp_df <- resp_df %>%
    mutate(id = game_id) %>%
    mutate(league = "nfl")
    NFL_movement_2018_df = rbind(NFL_movement_2018_df, resp_df)
    
  }

```


```{r}
NFL_movement_2020_df = NULL

for (id in NFL2020$id) {
  
  game_id = id
  url = "https://api.actionnetwork.com/web/v1/games/"
  url = paste(url, game_id, "/oddshistory")
  resp = GET(url, user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko)    Chrome/106.0.0.0 Safari/537.36"))
  resp_df = jsonlite::fromJSON(content(resp, "text"))$odds
  resp_df <- resp_df %>%
    mutate(id = game_id) %>%
    mutate(league = "nfl")
    NFL_movement_2020_df = rbind(NFL_movement_2020_df, resp_df)
    
  }

```
```{r}
NFL_movement_2016_df = NULL

for (id in NFL2016$id) {
  
  game_id = id
  url = "https://api.actionnetwork.com/web/v1/games/"
  url = paste(url, game_id, "/oddshistory")
  resp = GET(url, user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko)    Chrome/106.0.0.0 Safari/537.36"))
  resp_df = jsonlite::fromJSON(content(resp, "text"))$odds
  resp_df <- resp_df %>%
    mutate(id = game_id) %>%
    mutate(league = "nfl")
    NFL_movement_2016_df = rbind(NFL_movement_2016_df, resp_df)

  print(paste("finished game",id))
}


```

```{r}
NFL_movement_2015_df = NULL

for (id in NFL2015$id) {
  
  game_id = id
  url = "https://api.actionnetwork.com/web/v1/games/"
  url = paste(url, game_id, "/oddshistory")
  resp = GET(url, user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko)    Chrome/106.0.0.0 Safari/537.36"))
  resp_df = jsonlite::fromJSON(content(resp, "text"))$odds
  resp_df <- resp_df %>%
    mutate(id = game_id) %>%
    mutate(league = "nfl")
    NFL_movement_2015_df = rbind(NFL_movement_2015_df, resp_df)

  print(paste("finished game",id))
}

```

```{r}
NFL_movement_2014_df = NULL

for (id in NFL2014$id) {
  
  game_id = id
  url = "https://api.actionnetwork.com/web/v1/games/"
  url = paste(url, game_id, "/oddshistory")
  resp = GET(url, user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko)    Chrome/106.0.0.0 Safari/537.36"))
  resp_df = jsonlite::fromJSON(content(resp, "text"))$odds
  resp_df <- resp_df %>%
    mutate(id = game_id) %>%
    mutate(league = "nfl")
    NFL_movement_2014_df = rbind(NFL_movement_2014_df, resp_df)

  print(paste("finished game",id))
}

```

```{r}
NFL_movement_2013_df = NULL

for (id in NFL2013$id) {
  
  game_id = id
  url = "https://api.actionnetwork.com/web/v1/games/"
  url = paste(url, game_id, "/oddshistory")
  resp = GET(url, user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko)    Chrome/106.0.0.0 Safari/537.36"))
  resp_df = jsonlite::fromJSON(content(resp, "text"))$odds
  resp_df <- resp_df %>%
    mutate(id = game_id) %>%
    mutate(league = "nfl")
    NFL_movement_2013_df = rbind(NFL_movement_2013_df, resp_df)

  print(paste("finished game",id))
}

```

```{r}
NFL_movement_2012_df = NULL

for (id in NFL2012$id) {
  
  game_id = id
  url = "https://api.actionnetwork.com/web/v1/games/"
  url = paste(url, game_id, "/oddshistory")
  resp = GET(url, user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko)    Chrome/106.0.0.0 Safari/537.36"))
  resp_df = jsonlite::fromJSON(content(resp, "text"))$odds
  resp_df <- resp_df %>%
    mutate(id = game_id) %>%
    mutate(league = "nfl")
    NFL_movement_2012_df = rbind(NFL_movement_2012_df, resp_df)

  print(paste("finished game",id))
}

```

```{r}
NCAAF_movement_df = NULL

for (id in NCAAF$id) {
  
  game_id = id
  url = "https://api.actionnetwork.com/web/v1/games/"
  url = paste(url, game_id, "/oddshistory")
  resp = GET(url, user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko)    Chrome/106.0.0.0 Safari/537.36"))
  resp_df = jsonlite::fromJSON(content(resp, "text"))$odds
  resp_df <- resp_df %>%
    mutate(id = game_id) %>%
    mutate(league = "ncaal")
    NCAAF_movement_df = rbind(NCAAF_movement_df, resp_df)
  }


```

```{r}
MLB_movement_df = NULL

for (id in MLB$id) {
  
  game_id = id
  url = "https://api.actionnetwork.com/web/v1/games/"
  url = paste(url, game_id, "/oddshistory")
  resp = GET(url, user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko)    Chrome/106.0.0.0 Safari/537.36"))
  resp_df = jsonlite::fromJSON(content(resp, "text"))$odds
  resp_df <- resp_df %>%
    mutate(id = game_id) %>%
    mutate(league = "mlb")
    MLB_movement_df = rbind(MLB_movement_df, resp_df)
  }


```

```{r}
NHL_movement_df = NULL

for (id in NHL$id) {
  
  game_id = id
  url = "https://api.actionnetwork.com/web/v1/games/"
  url = paste(url, game_id, "/oddshistory")
  resp = GET(url, user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko)    Chrome/106.0.0.0 Safari/537.36"))
  resp_df = jsonlite::fromJSON(content(resp, "text"))$odds
  resp_df <- do.call(cbind.data.frame, resp_df)
  resp_df <- resp_df %>%
    mutate(id = game_id) %>%
    mutate(league = "nhl")
    NHL_movement_df = rbind(NHL_movement_df, resp_df)
    
    Sys.sleep(1)
    print(paste("finished game",id))
  }



```

```{r}
NBA_movement_df = NULL

for (id in NBA$id) {
  
  game_id = id
  url = "https://api.actionnetwork.com/web/v1/games/"
  url = paste(url, game_id, "/oddshistory")
  resp = GET(url, user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko)    Chrome/106.0.0.0 Safari/537.36"))
  resp_df = jsonlite::fromJSON(content(resp, "text"))$odds
  resp_df <- do.call(cbind.data.frame, resp_df)
  resp_df <- resp_df %>%
    mutate(id = game_id) %>%
    mutate(league = "nba")
    NBA_movement_df = rbind(NBA_movement_df, resp_df)
    
    print(paste("finished game",id))
  }


```

```{r}
#save(NFL_movement_df, file = "NFL_movement_df.rdata")
#save(NFL_movement_2018_df, file = "NFL_2018_movement_df.rdata")
#save(NFL_movement_2020_df, file = "NFL_2020_movement_df.rdata")
save(NFL_movement_2016_df, file = "NFL_movement_2016_df.rdata")
save(NFL_movement_2015_df, file = "NFL_movement_2016_df.rdata")
save(NFL_movement_2014_df, file = "NFL_movement_2016_df.rdata")
save(NFL_movement_2013_df, file = "NFL_movement_2016_df.rdata")
save(NFL_movement_2012_df, file = "NFL_movement_2016_df.rdata")
save(NCAAF_movement_df, file = "NCAAF_movement_df.rdata")
save(MLB_movement_df, file = "MLB_movement_df.rdata")
```
```{r}
save(NHL_movement_df, file = "NHL_movement_df.rdata")
save(NBA_movement_df, file = "NBA_movement_df.rdata")
```


```{r}
game_id = 107212
  url = "https://api.actionnetwork.com/web/v1/games/"
  url = paste(url, game_id, "/oddshistory")
  resp = GET(url, user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko)    Chrome/106.0.0.0 Safari/537.36"))
  resp_df = jsonlite::fromJSON(content(resp, "text"))$odds
  resp_df <- do.call(cbind.data.frame, resp_df)
```

