---
title: "Clean Data"
output: html_document
date: '2022-11-18'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("data_scraper.R")
```


```{r warning=FALSE}
line.to.prob = function(line) {
  
  if_else(line < 0,
          abs(line) / (abs(line) + 100) * 100,
          100 / (line + 100) * 100)
  
}

implied.prob = function(line1, line2) {
  prob1 = line.to.prob(line1)
  prob2 = line.to.prob(line2)
  
  return(prob1 / (prob1 + prob2))
}

clean_betting_data = function(betting_data) {
  betting_data = betting_data %>%
    filter(is.na(draw)) %>%
    mutate(ml_home_implied_prob = implied.prob(ml_home, ml_away),
           ml_away_implied_prob = implied.prob(ml_away, ml_home),
           spread_away_line_implied_prob = implied.prob(spread_away_line, spread_home_line),
           spread_home_line_inmplied_prob = implied.prob(spread_home_line, spread_away_line),
           over_implied_prob = implied.prob(over, under),
           under_implied_prob = implied.prob(under, over),
           away_over_implied_prob = implied.prob(away_over, away_under),
           away_under_implied_prob = implied.prob(away_under, away_over),
           home_over_implied_prob = implied.prob(home_over, home_under),
           home_under_implied_prob = implied.prob(home_under, home_over))
  
  return(betting_data)
}

get_ml_df = function(betting_data) {
  betting_data = betting_data %>%
    select(id, away_team_id, home_team_id, 
           winning_team_id, league_name, season, 
           ml_away, ml_home, ml_home_implied_prob, 
           ml_away_implied_prob, book_id) %>%
    filter(!is.na(winning_team_id),
           !is.na(ml_home_implied_prob),
           book_id != 15,
           book_id != 30) %>%
    mutate(home_team_win = if_else(winning_team_id == home_team_id, TRUE, FALSE),
           favorite_win_prob = pmax(ml_home_implied_prob, ml_away_implied_prob),
           favorite_home = if_else(favorite_win_prob == ml_home_implied_prob, T, F),
           favorite_win = if_else((favorite_home & home_team_win) | (!favorite_home & !home_team_win), T, F),
           brier_score = (favorite_win_prob - favorite_win) ^ 2)
  return(betting_data)
}

save_dfs = function(league) {
  leagues = "all"
  books = "all"
  start_year = 2022
  end_year = 2022
  is_clv = FALSE
  betting_df = get_betting_data(league, books, start_year, end_year, is_clv) %>% 
    clean_betting_data()
  save(betting_df, file = paste("betting_data/", league, "_raw.rdata",sep = ""))
  betting_df = betting_df %>% 
    get_ml_df()
  save(betting_df, file = paste("betting_data/", league, "_ml.rdata",sep = ""))
}


leagues = c("nfl", "ncaaf", "nhl", "mlb", "ncaab", "nba")

map(
  leagues,
  save_dfs
)
```

