---
title: "Untitled"
output: html_document
date: '2022-12-01'
---


# NCAAF



```{r warning=FALSE}
source()
constructor(ncaaf_ml, 2022)

get_model_brier_score = function(model_name) {
  if (model_name %in% c("lasso", "ridge")) {
    lasso = model_name == "lasso"
    return(fit_reg_log_model(lasso)$metrics %>% filter(metric == "brier_score"))
  } else {
    model_func = switch (model_name,
      "weighted average" = function(n) { fit_top_n_books_model(n, TRUE) },
      "average" = function(n) { fit_top_n_books_model(n, FALSE) },
      "logistic" = fit_logistic_model)
    vec = c()
    for (n in c("all", "above average")) {
      vec = rbind(vec, model_func(n)$metrics %>% 
                    filter(metric == "brier_score")) 
    }
    for (n in c(7:1)) {
      vec = rbind(vec, model_func(n)$metrics %>% 
                    filter(metric == "brier_score")) 
    }
    return(vec)
  }
}

get_model_brier_score("logistic")

brier_vec = c()
for (model in c("lasso", "ridge", "weighted average", "average", "logistic")) {
  brier_vec = rbind(brier_vec, get_model_brier_score(model))
}

brier_vec %>%
  arrange(value)
```

```{r}
average_vec
```

